/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health/live': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness: the process is up (no dependency checks). */
    get: operations['getHealthLive']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Readiness: database reachable and migrated (worker: job loop heartbeat). */
    get: operations['getHealthReady']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create an account
     * @description Always answers 202 for a well-formed request with an allowed email domain (disposable-email providers: 422 email_domain_not_allowed): a new account gets a confirmation email, an already registered address gets a hint email instead (no user enumeration). Sign in afterwards with POST /auth/login.
     */
    post: operations['Register']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Sign in with email and password
     * @description Sets the session cookie, or answers twoFactorRequired (second step: POST /auth/login/2fa). Failures are 401 invalid_credentials; after 5 failures in a row the account is locked for 15 minutes (still answered as invalid_credentials).
     */
    post: operations['Login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login/2fa': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Second login step: authenticator code or recovery code
     * @description Needs the pending-login cookie from POST /auth/login (twoFactorRequired, valid 5 minutes); without it 401 unauthenticated. Wrong codes are 401 invalid_credentials and count towards the lockout; each recovery code works once.
     */
    post: operations['LoginTwoFactor']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** End the session (clears the session cookie) */
    post: operations['Logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/confirm-email': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Confirm an email address with the token from the confirmation link */
    post: operations['ConfirmEmail']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/confirm-email/resend': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Send the confirmation email again to the signed-in user (no-op when already confirmed) */
    post: operations['ResendEmailConfirmation']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/forgot-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Request a password reset email
     * @description Always answers 202 (no user enumeration); only registered addresses receive an email.
     */
    post: operations['ForgotPassword']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/reset-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set a new password with the token from the reset link
     * @description Also confirms the email address (the link proved ownership), lifts a lockout and ends all other sessions.
     */
    post: operations['ResetPassword']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The signed-in user */
    get: operations['GetMe']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me/two-factor': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Two-factor authentication status */
    get: operations['GetTwoFactorStatus']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me/two-factor/setup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a new authenticator secret (QR code URI); 409 while 2FA is enabled */
    post: operations['SetUpTwoFactor']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me/two-factor/enable': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Turn on 2FA with a current authenticator code; returns the recovery codes once */
    post: operations['EnableTwoFactor']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me/two-factor/disable': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Turn off 2FA (confirm with password or code; no-op when off) */
    post: operations['DisableTwoFactor']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me/two-factor/recovery-codes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Replace all recovery codes (confirm with password or code); returns the new codes once */
    post: operations['RegenerateRecoveryCodes']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ConfirmEmailRequest: {
      /** Format: uuid */
      userId: string
      token: string
    }
    EnableTwoFactorRequest: {
      code: string
    }
    /**
     * @description Stable machine-readable error code (part of the contract; never renamed).
     * @enum {string}
     */
    ErrorCode:
      | 'bad_request'
      | 'calendar_frozen'
      | 'conflict'
      | 'csrf_header_missing'
      | 'email_domain_not_allowed'
      | 'email_not_verified'
      | 'external_sharing_not_allowed'
      | 'feature_not_in_plan'
      | 'insufficient_permission'
      | 'internal_error'
      | 'invalid_credentials'
      | 'method_not_allowed'
      | 'not_found'
      | 'override_invalid_in_target'
      | 'payload_too_large'
      | 'permission_self_lockout'
      | 'plan_limit_reached'
      | 'precondition_failed'
      | 'precondition_required'
      | 'rate_limited'
      | 'reauthentication_failed'
      | 'recurrence_invalid'
      | 'service_unavailable'
      | 'time_zone_invalid'
      | 'token_expired'
      | 'token_invalid'
      | 'two_factor_required'
      | 'uid_conflict'
      | 'unauthenticated'
      | 'unsupported_media_type'
      | 'validation_failed'
    ForgotPasswordRequest: {
      email: string
    }
    HealthResponse: {
      status: string
      checks: {
        [key: string]: string
      }
    }
    HttpValidationProblemDetails: {
      type?: null | string
      title?: null | string
      /** Format: int32 */
      status?: null | number | string
      detail?: null | string
      instance?: null | string
      errors?: {
        [key: string]: string[]
      }
    }
    LoginRequest: {
      email: string
      password: string
      rememberMe?: boolean
    }
    LoginResponse: {
      twoFactorRequired: boolean
      user: null | components['schemas']['MeResponse']
    }
    LoginTwoFactorRequest: {
      code?: null | string
      recoveryCode?: null | string
      rememberMe?: boolean
    }
    MeResponse: {
      /** Format: uuid */
      id: string
      email: string
      emailVerified: boolean
      displayName: string
      locale: string
      timeZone: string
      weekStart: string
      twoFactorEnabled: boolean
      /** Format: date-time */
      createdAt: string
    }
    /** @description RFC 9457 problem details. Further members depend on the code (e.g. `limit`, `required`, `actual`). */
    ProblemDetails: {
      /** Format: uri */
      type: string
      title: string
      /** Format: int32 */
      status: number
      detail?: string
      instance?: string
      code: components['schemas']['ErrorCode']
      traceId?: string
      /** @description Validation errors by field (code `validation_failed`). */
      errors?: {
        [key: string]: string[]
      }
    }
    ReauthenticationRequest: {
      password?: null | string
      code?: null | string
    }
    RecoveryCodesResponse: {
      recoveryCodes: string[]
    }
    RegisterRequest: {
      email: string
      password: string
      displayName: string
      locale?: null | string
      timeZone?: null | string
    }
    ResetPasswordRequest: {
      /** Format: uuid */
      userId: string
      token: string
      newPassword: string
    }
    TwoFactorSetupResponse: {
      sharedKey: string
      authenticatorUri: string
    }
    TwoFactorStatusResponse: {
      enabled: boolean
      /** Format: int32 */
      recoveryCodesLeft: number | string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealthLive: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  getHealthReady: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  Register: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest']
      }
    }
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  Login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  LoginTwoFactor: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginTwoFactorRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  Logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  ConfirmEmail: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfirmEmailRequest']
      }
    }
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  ResendEmailConfirmation: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  ForgotPassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ForgotPasswordRequest']
      }
    }
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  ResetPassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordRequest']
      }
    }
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  GetMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  GetTwoFactorStatus: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TwoFactorStatusResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  SetUpTwoFactor: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TwoFactorSetupResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  EnableTwoFactor: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EnableTwoFactorRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecoveryCodesResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  DisableTwoFactor: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReauthenticationRequest']
      }
    }
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  RegenerateRecoveryCodes: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReauthenticationRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecoveryCodesResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
}
