/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health/live': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness: the process is up (no dependency checks). */
    get: operations['getHealthLive']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Readiness: database reachable and migrated (worker: job loop heartbeat). */
    get: operations['getHealthReady']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create an account
     * @description Always answers 202 for a well-formed request with an allowed email domain (disposable-email providers: 422 email_domain_not_allowed): a new account gets a confirmation email, an already registered address gets a hint email instead (no user enumeration). Sign in afterwards with POST /auth/login.
     */
    post: operations['Register']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Sign in with email and password
     * @description Sets the session cookie, or answers twoFactorRequired (second step: POST /auth/login/2fa). Failures are 401 invalid_credentials; after 5 failures in a row the account is locked for 15 minutes (still answered as invalid_credentials).
     */
    post: operations['Login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login/2fa': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Second login step: authenticator code or recovery code
     * @description Needs the pending-login cookie from POST /auth/login (twoFactorRequired, valid 5 minutes); without it 401 unauthenticated. Wrong codes are 401 invalid_credentials and count towards the lockout; each recovery code works once.
     */
    post: operations['LoginTwoFactor']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** End the session (clears the session cookie) */
    post: operations['Logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/confirm-email': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Confirm an email address with the token from the confirmation link */
    post: operations['ConfirmEmail']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/confirm-email/resend': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Send the confirmation email again to the signed-in user (no-op when already confirmed) */
    post: operations['ResendEmailConfirmation']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/forgot-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Request a password reset email
     * @description Always answers 202 (no user enumeration); only registered addresses receive an email.
     */
    post: operations['ForgotPassword']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/reset-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set a new password with the token from the reset link
     * @description Also confirms the email address (the link proved ownership), lifts a lockout and ends all other sessions.
     */
    post: operations['ResetPassword']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The signed-in user (with ETag) */
    get: operations['GetMe']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Update profile settings (JSON Merge Patch, requires If-Match)
     * @description Absent or null members stay unchanged. Unknown time zones are 422 time_zone_invalid, unsupported locales and week starts 400 validation_failed. If-Match: the ETag of GET /me (or *); missing → 428 precondition_required, stale → 412 precondition_failed.
     */
    patch: operations['UpdateMe']
    trace?: never
  }
  '/api/v1/me/two-factor': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Two-factor authentication status */
    get: operations['GetTwoFactorStatus']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me/two-factor/setup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a new authenticator secret (QR code URI); 409 while 2FA is enabled */
    post: operations['SetUpTwoFactor']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me/two-factor/enable': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Turn on 2FA with a current authenticator code; returns the recovery codes once */
    post: operations['EnableTwoFactor']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me/two-factor/disable': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Turn off 2FA (confirm with password or code; no-op when off) */
    post: operations['DisableTwoFactor']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me/two-factor/recovery-codes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Replace all recovery codes (confirm with password or code); returns the new codes once */
    post: operations['RegenerateRecoveryCodes']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/groups': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * My groups with my role (cursor-paginated)
     * @description Ordered by creation. limit: 1–200 (default 50); cursor: nextCursor of the previous page.
     */
    get: operations['ListGroups']
    put?: never
    /** Create a group (the caller becomes owner and billing owner) */
    post: operations['CreateGroup']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/groups/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * A group I am a member of (with ETag)
     * @description 404 for groups the caller is not a member of (no existence leaks).
     */
    get: operations['GetGroup']
    put?: never
    post?: never
    /** Delete the group with its memberships and invites (owners only, requires If-Match) */
    delete: operations['DeleteGroup']
    options?: never
    head?: never
    /**
     * Rename or change settings (admins and owners; JSON Merge Patch, requires If-Match)
     * @description Absent or null members stay unchanged; an empty description removes it. Members and viewers: 403 insufficient_permission. If-Match: the ETag of GET /groups/{id} (or *).
     */
    patch: operations['UpdateGroup']
    trace?: never
  }
  '/api/v1/groups/{id}/members': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Members of a group (cursor-paginated)
     * @description Every member sees the list unless memberListVisibility is members_and_above (viewers: 403). Emails are only shown to admins and owners.
     */
    get: operations['ListGroupMembers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/groups/{id}/members/{userId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Remove a member, or leave the group with your own user id (requires If-Match)
     * @description Owners remove anyone, admins members and viewers; everyone may leave. Last-owner and billing-owner protection as for role changes. revokeEventShares (default true): also revoke the member's individual event shares on the group's calendars.
     */
    delete: operations['RemoveGroupMember']
    options?: never
    head?: never
    /**
     * Change a member's role (requires If-Match)
     * @description Owners assign any role; admins manage members and viewers only and assign at most member (only owners promote to admin or owner); everyone may lower their own role. The last owner cannot be demoted (409 last_owner), the billing owner only after transferring billing (409 billing_owner_transfer_required); frozen groups refuse role changes (409 group_frozen). revokeEventShares (default true): on demotion also revoke the member's individual event shares on the group's calendars.
     */
    patch: operations['ChangeGroupMemberRole']
    trace?: never
  }
  '/api/v1/groups/{id}/transfer': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Make another owner the billing owner (billing owner only)
     * @description The recipient must be a member with role owner (409 billing_owner_must_be_owner); their plan governs the group from now on.
     */
    post: operations['TransferGroupBilling']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/groups/{id}/invites': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Pending invites of a group (admins and owners, cursor-paginated) */
    get: operations['ListGroupInvites']
    put?: never
    /**
     * Invite by email or create an invite link (admins and owners)
     * @description With email: a single-use invite sent to that address (en/de), usable only by an account whose verified email matches; a new invite replaces pending ones for the address. Without email: an invite link (role at most member, maxUses 1–1000, default 50) returned once in url. role: owners invite any role, admins up to member. expiresInDays: 1–30 (default 14 for email, 7 for links). Frozen groups: 409 group_frozen.
     */
    post: operations['CreateGroupInvite']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/invites/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Revoke an invite (admins and owners; idempotent)
     * @description Admins can revoke invites with roles up to member. Revoking an expired, used or revoked invite is a no-op.
     */
    delete: operations['RevokeGroupInvite']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/invites/accept': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Join a group with an invite token
     * @description Needs a verified email address (403 email_not_verified); email invites only for the invited address (403 invite_email_mismatch). Unknown, expired, revoked and used-up tokens are 400 token_invalid alike. Members accepting again keep their role. Returns the group.
     */
    post: operations['AcceptGroupInvite']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AcceptInviteRequest: {
      token: string
    }
    ChangeMemberRoleRequest: {
      role: string
    }
    ConfirmEmailRequest: {
      /** Format: uuid */
      userId: string
      token: string
    }
    CreateGroupRequest: {
      name: string
      description?: null | string
    }
    CreateInviteRequest: {
      email?: null | string
      role: string
      /** Format: int32 */
      expiresInDays?: null | number | string
      /** Format: int32 */
      maxUses?: null | number | string
    }
    CreateInviteResponse: {
      invite: components['schemas']['InviteResponse']
      url: null | string
    }
    EnableTwoFactorRequest: {
      code: string
    }
    /**
     * @description Stable machine-readable error code (part of the contract; never renamed).
     * @enum {string}
     */
    ErrorCode:
      | 'bad_request'
      | 'billing_owner_must_be_owner'
      | 'billing_owner_transfer_required'
      | 'calendar_frozen'
      | 'conflict'
      | 'csrf_header_missing'
      | 'email_domain_not_allowed'
      | 'email_not_verified'
      | 'external_sharing_not_allowed'
      | 'feature_not_in_plan'
      | 'group_frozen'
      | 'insufficient_permission'
      | 'internal_error'
      | 'invalid_credentials'
      | 'invite_email_mismatch'
      | 'last_owner'
      | 'method_not_allowed'
      | 'not_found'
      | 'override_invalid_in_target'
      | 'payload_too_large'
      | 'permission_self_lockout'
      | 'plan_limit_reached'
      | 'precondition_failed'
      | 'precondition_required'
      | 'rate_limited'
      | 'reauthentication_failed'
      | 'recurrence_invalid'
      | 'service_unavailable'
      | 'time_zone_invalid'
      | 'token_expired'
      | 'token_invalid'
      | 'two_factor_required'
      | 'uid_conflict'
      | 'unauthenticated'
      | 'unsupported_media_type'
      | 'validation_failed'
    ForgotPasswordRequest: {
      email: string
    }
    GroupListResponse: {
      items: components['schemas']['GroupResponse'][]
      nextCursor: null | string
    }
    GroupResponse: {
      /** Format: uuid */
      id: string
      name: string
      description: null | string
      myRole: string
      /** Format: uuid */
      billingOwnerId: string
      /** Format: int32 */
      memberCount: number | string
      memberListVisibility: string
      frozen: boolean
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
    }
    HealthResponse: {
      status: string
      checks: {
        [key: string]: string
      }
    }
    HttpValidationProblemDetails: {
      type?: null | string
      title?: null | string
      /** Format: int32 */
      status?: null | number | string
      detail?: null | string
      instance?: null | string
      errors?: {
        [key: string]: string[]
      }
    }
    InviteListResponse: {
      items: components['schemas']['InviteResponse'][]
      nextCursor: null | string
    }
    InviteResponse: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      groupId: string
      kind: string
      email: null | string
      role: string
      /** Format: int32 */
      maxUses: number | string
      /** Format: int32 */
      uses: number | string
      /** Format: date-time */
      expiresAt: string
      /** Format: uuid */
      createdBy: string
      /** Format: date-time */
      createdAt: string
    }
    LoginRequest: {
      email: string
      password: string
      rememberMe?: boolean
    }
    LoginResponse: {
      twoFactorRequired: boolean
      user: null | components['schemas']['MeResponse']
    }
    LoginTwoFactorRequest: {
      code?: null | string
      recoveryCode?: null | string
      rememberMe?: boolean
    }
    MemberListResponse: {
      items: components['schemas']['MemberResponse'][]
      nextCursor: null | string
    }
    MemberResponse: {
      /** Format: uuid */
      userId: string
      displayName: string
      email: null | string
      role: string
      isBillingOwner: boolean
      /** Format: date-time */
      joinedAt: string
      etag: string
    }
    MeResponse: {
      /** Format: uuid */
      id: string
      email: string
      emailVerified: boolean
      displayName: string
      locale: string
      timeZone: string
      weekStart: string
      twoFactorEnabled: boolean
      /** Format: date-time */
      createdAt: string
    }
    /** @description RFC 9457 problem details. Further members depend on the code (e.g. `limit`, `required`, `actual`). */
    ProblemDetails: {
      /** Format: uri */
      type: string
      title: string
      /** Format: int32 */
      status: number
      detail?: string
      instance?: string
      code: components['schemas']['ErrorCode']
      traceId?: string
      /** @description Validation errors by field (code `validation_failed`). */
      errors?: {
        [key: string]: string[]
      }
    }
    ReauthenticationRequest: {
      password?: null | string
      code?: null | string
    }
    RecoveryCodesResponse: {
      recoveryCodes: string[]
    }
    RegisterRequest: {
      email: string
      password: string
      displayName: string
      locale?: null | string
      timeZone?: null | string
    }
    ResetPasswordRequest: {
      /** Format: uuid */
      userId: string
      token: string
      newPassword: string
    }
    TransferBillingRequest: {
      /** Format: uuid */
      userId: string
    }
    TwoFactorSetupResponse: {
      sharedKey: string
      authenticatorUri: string
    }
    TwoFactorStatusResponse: {
      enabled: boolean
      /** Format: int32 */
      recoveryCodesLeft: number | string
    }
    UpdateGroupRequest: {
      name?: null | string
      description?: null | string
      memberListVisibility?: null | string
    }
    UpdateProfileRequest: {
      displayName?: null | string
      locale?: null | string
      timeZone?: null | string
      weekStart?: null | string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealthLive: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  getHealthReady: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  Register: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest']
      }
    }
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  Login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  LoginTwoFactor: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginTwoFactorRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  Logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  ConfirmEmail: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfirmEmailRequest']
      }
    }
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  ResendEmailConfirmation: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  ForgotPassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ForgotPasswordRequest']
      }
    }
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  ResetPassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordRequest']
      }
    }
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  GetMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  UpdateMe: {
    parameters: {
      query?: never
      header?: {
        'If-Match'?: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/merge-patch+json': components['schemas']['UpdateProfileRequest']
        'application/json': components['schemas']['UpdateProfileRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  GetTwoFactorStatus: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TwoFactorStatusResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  SetUpTwoFactor: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TwoFactorSetupResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  EnableTwoFactor: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EnableTwoFactorRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecoveryCodesResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  DisableTwoFactor: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReauthenticationRequest']
      }
    }
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  RegenerateRecoveryCodes: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReauthenticationRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecoveryCodesResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  ListGroups: {
    parameters: {
      query?: {
        limit?: number | string
        cursor?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupListResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  CreateGroup: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateGroupRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  GetGroup: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  DeleteGroup: {
    parameters: {
      query?: never
      header?: {
        'If-Match'?: string
      }
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  UpdateGroup: {
    parameters: {
      query?: never
      header?: {
        'If-Match'?: string
      }
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/merge-patch+json': components['schemas']['UpdateGroupRequest']
        'application/json': components['schemas']['UpdateGroupRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  ListGroupMembers: {
    parameters: {
      query?: {
        limit?: number | string
        cursor?: string
      }
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MemberListResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  RemoveGroupMember: {
    parameters: {
      query?: {
        revokeEventShares?: boolean
      }
      header?: {
        'If-Match'?: string
      }
      path: {
        id: string
        userId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  ChangeGroupMemberRole: {
    parameters: {
      query?: {
        revokeEventShares?: boolean
      }
      header?: {
        'If-Match'?: string
      }
      path: {
        id: string
        userId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangeMemberRoleRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MemberResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  TransferGroupBilling: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TransferBillingRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  ListGroupInvites: {
    parameters: {
      query?: {
        limit?: number | string
        cursor?: string
      }
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InviteListResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  CreateGroupInvite: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateInviteRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CreateInviteResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  RevokeGroupInvite: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  AcceptGroupInvite: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AcceptInviteRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GroupResponse']
        }
      }
      /** @description Error (RFC 9457 problem details with a stable `code`). */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
}
