/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health/live': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness: the process is up (no dependency checks). */
    get: operations['getHealthLive']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Readiness: database reachable and migrated (worker: job loop heartbeat). */
    get: operations['getHealthReady']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * @description Stable machine-readable error code (part of the contract; never renamed).
     * @enum {string}
     */
    ErrorCode:
      | 'bad_request'
      | 'calendar_frozen'
      | 'conflict'
      | 'email_not_verified'
      | 'external_sharing_not_allowed'
      | 'feature_not_in_plan'
      | 'insufficient_permission'
      | 'internal_error'
      | 'method_not_allowed'
      | 'not_found'
      | 'override_invalid_in_target'
      | 'payload_too_large'
      | 'permission_self_lockout'
      | 'plan_limit_reached'
      | 'precondition_failed'
      | 'precondition_required'
      | 'rate_limited'
      | 'recurrence_invalid'
      | 'service_unavailable'
      | 'time_zone_invalid'
      | 'token_expired'
      | 'two_factor_required'
      | 'uid_conflict'
      | 'unauthenticated'
      | 'unsupported_media_type'
      | 'validation_failed'
    HealthResponse: {
      status: string
      checks: {
        [key: string]: string
      }
    }
    /** @description RFC 9457 problem details. Further members depend on the code (e.g. `limit`, `required`, `actual`). */
    ProblemDetails: {
      /** Format: uri */
      type: string
      title: string
      /** Format: int32 */
      status: number
      detail?: string
      instance?: string
      code: components['schemas']['ErrorCode']
      traceId?: string
      /** @description Validation errors by field (code `validation_failed`). */
      errors?: {
        [key: string]: string[]
      }
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealthLive: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  getHealthReady: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
}
